### ISSUE TITLE
Travis tests are not running

### ISSUE THREAD

**Issue by filipmelik** [dfridrich/Ares#24]
Wrong configuration prevents running phpunit tests. More importantly, the tests act like they were successful, but that is just because no tests were really executed. 

For example see https://travis-ci.org/dfridrich/Ares/jobs/510557015

**Comment by dfridrich** [comment]
Can you provide fix?

**Comment by filipmelik** [comment]
Will try later this week, but not promising anything, i have to find out how to work with travis first
