### ISSUE TITLE
Návrh na doplnění a změnu

### ISSUE THREAD

**Issue by zachrdlapetr** [dfridrich/Ares#25]
V nette vyhazuje metoda findById z třídy Justice chybu, že IČO není integer, ale jako integer vkládané je. 

`$ares = new \Defr\Ares();
$record = $ares->findByIdentificationNumber(27755941); 
$people = $record->getCompanyPeople(); `

Navrhuji drobné doplnění 

`public function findById(int $id)`

Projde to pak Assertion:integer testem

V metodě extractDetailUrlFromCrawler stejné třídy navrhuji změnu $href[1] na $href[0], protože jinak to vrací úplné výsledky, ale samozřejmě neaktuální.

**Comment by petrparolek** [comment]
IČO nemůže být integer, protože může začínat 0

**Comment by zachrdlapetr** [comment]
Aha. Ale pak nedává smysl  Assertion::integer($id); na lince 50 třídy Justice.

**Comment by petrparolek** [comment]
např. moje IČO začíná nulou

**Comment by zachrdlapetr** [comment]
Jde jen o chybu, která se objevuje jen v nette. Šlo by to pak napravit Assertion::integer((int) $id);  výjimka bude ok a ič s 0 na začátku taky

**Comment by petrparolek** [comment]
pull request je vítaný

**Comment by zachrdlapetr** [comment]
tak to je metafyzika o které nemám tušení :)  fakt to zatím neumím. jedeme na subversion.
